# This is a generated file. Not intended for manual editing.
services:
  weatherapi:
    build:
      context: "/Users/mike/Developer/WeatherAPI"
      dockerfile: "WeatherAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WeatherAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "weatherapi:dev"
    ports: []
    volumes:
    - "/Users/mike/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/mike/Developer/WeatherAPI/WeatherAPI:/app:rw"
    - "/Users/mike/Developer/WeatherAPI:/src:rw"
    working_dir: "/app"
